####################################
# /TinyDB
####################################
GET http://127.0.0.1:5000/tinydb

##################
GET http://127.0.0.1:5000/tinydb/jupyternb

##################
POST http://127.0.0.1:5000/tinydb/test
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

##################
POST http://127.0.0.1:5000/tinydb/ngrok
content-type: application/json

{
    "authtoken": "73C1ae7cc3uQWWr1Lx3UB_7PgR3q3dCxcfmD4FqpebF",
    "addr": 8888
}
##################
GET http://127.0.0.1:5000/tinydb/ngrok/1


##################
DELETE http://127.0.0.1:5000/tinydb/inventory/4

####################################
# Ngrok
####################################
POST http://127.0.0.1:3000/ngrok
content-type: application/json

{
  "authtoken": "73C1ae7cc3uQWWr1Lx3UB_7PgR3q3dCxcfmD4FqpebF",
  "addr": 5000
}

####################################
GET http://127.0.0.1:5000/ngrok

####################################
# Download
####################################
GET http://127.0.0.1:5000/download/Demirbaş/15112486034535072-Belgeler.xlsx


####################################
# opc
####################################
# List OPC servers
GET http://127.0.0.1:5000/opc

####################################
# Create opc client
POST http://127.0.0.1:5000/opc/OPC.IwSCP.1

####################################
# Status of opc client
GET  http://127.0.0.1:5000/opc/OPC.IwSCP.1

####################################
# Read item
# GET  http://127.0.0.1:5000/opc/OPC.IwSCP.1/!I4,HCS02.1,Plc.PVL,.z_pos_hizi
GET  http://127.0.0.1:5000/opc/OPC.IwSCP.1/!BOOL,HCS02.1,Plc.PVL,.yatay_tarama_op
####################################
# Write item
# PUT  http://127.0.0.1:5000/opc/OPC.IwSCP.1/!I4,HCS02.1,Plc.PVL,.z_pos_hizi
# content-type: application/json

# {
#   "value": 10002
# }

PUT  http://127.0.0.1:5000/opc/OPC.IwSCP.1/!I4,HCS02.1,Plc.PVL,.yatay_tarama_op
content-type: application/json

{
  "value": "false"
}